version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: docker_doc
      MYSQL_USER: db_client
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./src/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: db_client
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: docker_doc_dev
    volumes:
      - ./src:/var/www/html

volumes:
  db_data:
